blank_issues_enabled: false
contact_links:
  - name: ğŸ¤” Question 
    url: https://github.com/TheFizFactor/comicers/discussions/new
    about: Ask a question about Comicers 
  - name: ğŸ”— Extensions repository
    url: https://github.com/TheFizFactor/comicers-extensions/issues/new/choose
    about: Reports/requests for extensions should be opened in the extensions repository
  - name: ğŸ–¥ï¸ Comicers website
    url: https://comicers.org
    about: Documentation for using Comicers
